-- Q4: Loyalty offer ROI by offer type and RFM segment
-- Business question: Which offer type drives better ROI for the At Risk segment?
-- Requires loyalty_offers table (generated by notebook 03 / data/processed/loyalty_offers.csv)
-- Campaign cost assumption: $0.50 per user targeted

SELECT
    offer_type,
    rfm_segment,
    COUNT(user_id)                                                          AS users_targeted,
    SUM(CASE WHEN converted = TRUE THEN 1 ELSE 0 END)                      AS conversions,
    ROUND(100.0 * SUM(CASE WHEN converted = TRUE THEN 1 ELSE 0 END)
        / COUNT(user_id), 1)                                                AS conversion_rate_pct,
    ROUND(AVG(CASE WHEN converted = TRUE THEN order_value END), 2)         AS avg_order_value,
    ROUND(SUM(CASE WHEN converted = TRUE THEN order_value ELSE 0 END), 2)  AS total_revenue,
    ROUND(
        SUM(CASE WHEN converted = TRUE THEN order_value ELSE 0 END)
        / NULLIF(COUNT(user_id) * 0.50, 0), 2
    )                                                                       AS roi_ratio
FROM loyalty_offers
GROUP BY offer_type, rfm_segment
ORDER BY rfm_segment, roi_ratio DESC;
